package com.example.homework.bean;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseId
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseName
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.InstituteId
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private Integer instituteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseCredit
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private Float courseCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseHours
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private Short courseHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseUrl
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private String courseUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseType
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private String courseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.Save1
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private String save1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.Save2
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private String save2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Course.CourseDetailed
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    private String courseDetailed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseId
     *
     * @return the value of Course.CourseId
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseId
     *
     * @param courseId the value for Course.CourseId
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseName
     *
     * @return the value of Course.CourseName
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseName
     *
     * @param courseName the value for Course.CourseName
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.InstituteId
     *
     * @return the value of Course.InstituteId
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public Integer getInstituteId() {
        return instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.InstituteId
     *
     * @param instituteId the value for Course.InstituteId
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseCredit
     *
     * @return the value of Course.CourseCredit
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public Float getCourseCredit() {
        return courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseCredit
     *
     * @param courseCredit the value for Course.CourseCredit
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseCredit(Float courseCredit) {
        this.courseCredit = courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseHours
     *
     * @return the value of Course.CourseHours
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public Short getCourseHours() {
        return courseHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseHours
     *
     * @param courseHours the value for Course.CourseHours
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseHours(Short courseHours) {
        this.courseHours = courseHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseUrl
     *
     * @return the value of Course.CourseUrl
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public String getCourseUrl() {
        return courseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseUrl
     *
     * @param courseUrl the value for Course.CourseUrl
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseUrl(String courseUrl) {
        this.courseUrl = courseUrl == null ? null : courseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseType
     *
     * @return the value of Course.CourseType
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseType
     *
     * @param courseType the value for Course.CourseType
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType == null ? null : courseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.Save1
     *
     * @return the value of Course.Save1
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public String getSave1() {
        return save1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.Save1
     *
     * @param save1 the value for Course.Save1
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setSave1(String save1) {
        this.save1 = save1 == null ? null : save1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.Save2
     *
     * @return the value of Course.Save2
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public String getSave2() {
        return save2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.Save2
     *
     * @param save2 the value for Course.Save2
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setSave2(String save2) {
        this.save2 = save2 == null ? null : save2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Course.CourseDetailed
     *
     * @return the value of Course.CourseDetailed
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public String getCourseDetailed() {
        return courseDetailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Course.CourseDetailed
     *
     * @param courseDetailed the value for Course.CourseDetailed
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    public void setCourseDetailed(String courseDetailed) {
        this.courseDetailed = courseDetailed == null ? null : courseDetailed.trim();
    }
}