package com.example.homework.bean;

public class Institute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Institute.InstituteId
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    private Integer instituteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Institute.InstituteName
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    private String instituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Institute.Is_delete
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    private Short is_delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Institute.InstituteId
     *
     * @return the value of Institute.InstituteId
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    public Integer getInstituteId() {
        return instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Institute.InstituteId
     *
     * @param instituteId the value for Institute.InstituteId
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Institute.InstituteName
     *
     * @return the value of Institute.InstituteName
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Institute.InstituteName
     *
     * @param instituteName the value for Institute.InstituteName
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName == null ? null : instituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Institute.Is_delete
     *
     * @return the value of Institute.Is_delete
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    public Short getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Institute.Is_delete
     *
     * @param is_delete the value for Institute.Is_delete
     *
     * @mbg.generated Sat Apr 11 16:02:06 CST 2020
     */
    public void setIs_delete(Short is_delete) {
        this.is_delete = is_delete;
    }
}