package com.example.homework.bean;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.NewsId
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.NewsTitle
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private String newsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.NewsTime
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private Date newsTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.NewsAuthor
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private String newsAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.Save1
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private String save1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.Save2
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private String save2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.Save3
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private String save3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column News.NewsContent
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    private String newsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.NewsId
     *
     * @return the value of News.NewsId
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.NewsId
     *
     * @param newsId the value for News.NewsId
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.NewsTitle
     *
     * @return the value of News.NewsTitle
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.NewsTitle
     *
     * @param newsTitle the value for News.NewsTitle
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.NewsTime
     *
     * @return the value of News.NewsTime
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public Date getNewsTime() {
        return newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.NewsTime
     *
     * @param newsTime the value for News.NewsTime
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setNewsTime(Date newsTime) {
        this.newsTime = newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.NewsAuthor
     *
     * @return the value of News.NewsAuthor
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public String getNewsAuthor() {
        return newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.NewsAuthor
     *
     * @param newsAuthor the value for News.NewsAuthor
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setNewsAuthor(String newsAuthor) {
        this.newsAuthor = newsAuthor == null ? null : newsAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.Save1
     *
     * @return the value of News.Save1
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public String getSave1() {
        return save1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.Save1
     *
     * @param save1 the value for News.Save1
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setSave1(String save1) {
        this.save1 = save1 == null ? null : save1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.Save2
     *
     * @return the value of News.Save2
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public String getSave2() {
        return save2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.Save2
     *
     * @param save2 the value for News.Save2
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setSave2(String save2) {
        this.save2 = save2 == null ? null : save2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.Save3
     *
     * @return the value of News.Save3
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public String getSave3() {
        return save3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.Save3
     *
     * @param save3 the value for News.Save3
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setSave3(String save3) {
        this.save3 = save3 == null ? null : save3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column News.NewsContent
     *
     * @return the value of News.NewsContent
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column News.NewsContent
     *
     * @param newsContent the value for News.NewsContent
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }
}