package com.example.homework.bean;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.StudentId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.StudentName
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Gender
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.StudentNative
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String studentNative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.InstituteId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer instituteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.StudentMajorId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer studentMajorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.StudentTel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer studentTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.StudentBirthday
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Date studentBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Password
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.AdmissionDate
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Date admissionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Location
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Is_delete
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer is_delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.StudentId
     *
     * @return the value of Student.StudentId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.StudentId
     *
     * @param studentId the value for Student.StudentId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.StudentName
     *
     * @return the value of Student.StudentName
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.StudentName
     *
     * @param studentName the value for Student.StudentName
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Gender
     *
     * @return the value of Student.Gender
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Gender
     *
     * @param gender the value for Student.Gender
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.StudentNative
     *
     * @return the value of Student.StudentNative
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getStudentNative() {
        return studentNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.StudentNative
     *
     * @param studentNative the value for Student.StudentNative
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setStudentNative(String studentNative) {
        this.studentNative = studentNative == null ? null : studentNative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.InstituteId
     *
     * @return the value of Student.InstituteId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getInstituteId() {
        return instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.InstituteId
     *
     * @param instituteId the value for Student.InstituteId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.StudentMajorId
     *
     * @return the value of Student.StudentMajorId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getStudentMajorId() {
        return studentMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.StudentMajorId
     *
     * @param studentMajorId the value for Student.StudentMajorId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setStudentMajorId(Integer studentMajorId) {
        this.studentMajorId = studentMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.StudentTel
     *
     * @return the value of Student.StudentTel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getStudentTel() {
        return studentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.StudentTel
     *
     * @param studentTel the value for Student.StudentTel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setStudentTel(Integer studentTel) {
        this.studentTel = studentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.StudentBirthday
     *
     * @return the value of Student.StudentBirthday
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Date getStudentBirthday() {
        return studentBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.StudentBirthday
     *
     * @param studentBirthday the value for Student.StudentBirthday
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setStudentBirthday(Date studentBirthday) {
        this.studentBirthday = studentBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Password
     *
     * @return the value of Student.Password
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Password
     *
     * @param password the value for Student.Password
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.AdmissionDate
     *
     * @return the value of Student.AdmissionDate
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Date getAdmissionDate() {
        return admissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.AdmissionDate
     *
     * @param admissionDate the value for Student.AdmissionDate
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Location
     *
     * @return the value of Student.Location
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Location
     *
     * @param location the value for Student.Location
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Is_delete
     *
     * @return the value of Student.Is_delete
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Is_delete
     *
     * @param is_delete the value for Student.Is_delete
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }
}