package com.example.homework.bean;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TeacherId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TeacherName
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.Gender
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TeacherNative
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String teacherNative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.InstituteId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer instituteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TeacherTel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Integer teacherTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TeacherBirthday
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Date teacherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.Password
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.EntryTime
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TeacherLevel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String teacherLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.Save1
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    private String save1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TeacherId
     *
     * @return the value of Teacher.TeacherId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TeacherId
     *
     * @param teacherId the value for Teacher.TeacherId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TeacherName
     *
     * @return the value of Teacher.TeacherName
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TeacherName
     *
     * @param teacherName the value for Teacher.TeacherName
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.Gender
     *
     * @return the value of Teacher.Gender
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.Gender
     *
     * @param gender the value for Teacher.Gender
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TeacherNative
     *
     * @return the value of Teacher.TeacherNative
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getTeacherNative() {
        return teacherNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TeacherNative
     *
     * @param teacherNative the value for Teacher.TeacherNative
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setTeacherNative(String teacherNative) {
        this.teacherNative = teacherNative == null ? null : teacherNative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.InstituteId
     *
     * @return the value of Teacher.InstituteId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getInstituteId() {
        return instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.InstituteId
     *
     * @param instituteId the value for Teacher.InstituteId
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TeacherTel
     *
     * @return the value of Teacher.TeacherTel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Integer getTeacherTel() {
        return teacherTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TeacherTel
     *
     * @param teacherTel the value for Teacher.TeacherTel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setTeacherTel(Integer teacherTel) {
        this.teacherTel = teacherTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TeacherBirthday
     *
     * @return the value of Teacher.TeacherBirthday
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Date getTeacherBirthday() {
        return teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TeacherBirthday
     *
     * @param teacherBirthday the value for Teacher.TeacherBirthday
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setTeacherBirthday(Date teacherBirthday) {
        this.teacherBirthday = teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.Password
     *
     * @return the value of Teacher.Password
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.Password
     *
     * @param password the value for Teacher.Password
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.EntryTime
     *
     * @return the value of Teacher.EntryTime
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.EntryTime
     *
     * @param entryTime the value for Teacher.EntryTime
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TeacherLevel
     *
     * @return the value of Teacher.TeacherLevel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getTeacherLevel() {
        return teacherLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TeacherLevel
     *
     * @param teacherLevel the value for Teacher.TeacherLevel
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setTeacherLevel(String teacherLevel) {
        this.teacherLevel = teacherLevel == null ? null : teacherLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.Save1
     *
     * @return the value of Teacher.Save1
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public String getSave1() {
        return save1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.Save1
     *
     * @param save1 the value for Teacher.Save1
     *
     * @mbggenerated Thu Apr 09 13:16:52 CST 2020
     */
    public void setSave1(String save1) {
        this.save1 = save1 == null ? null : save1.trim();
    }
}