package com.example.homework.sqlMapper;

import com.example.homework.bean.Course;
import com.example.homework.bean.CourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    long countByExample(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int deleteByExample(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    List<Course> selectByExampleWithBLOBs(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    List<Course> selectByExample(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    Course selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") Course record, @Param("example") CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Course record, @Param("example") CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int updateByExample(@Param("record") Course record, @Param("example") CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Sun Apr 12 16:55:29 CST 2020
     */
    int updateByPrimaryKey(Course record);
}