package com.example.homework.sqlMapper;

import com.example.homework.bean.News;
import com.example.homework.bean.NewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    long countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    List<News> selectByExampleWithBLOBs(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    News selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table News
     *
     * @mbg.generated Sat Apr 11 19:18:02 CST 2020
     */
    int updateByPrimaryKey(News record);
}